Repository apache/couchdb, pull requests merged in 2018-03, with the labels that each got.

#997 Allow couchspawnkillable to live in directories with spaces
  src/couchdb/couch_os_daemons.erl
  src/couchdb/couch_os_process.erl
Labels: 1.x

#1242 Allow couch_os_daemons to live in directories with spaces
  src/couch/src/couch_os_daemons.erl
Labels: windows

#1245 feat: add debug log output for shard open errors
  src/fabric/src/fabric_util.erl
Labels: enhancement
